name: GitHub Pagesへのデプロイ
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ブランチをチェックアウト
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: キャッシュの設定
        uses: actions/cache@v1
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-${{ github.ref }}-cache
      - name: パッケージインストール
        run: yarn install
      - name: 静的ビルド
        run: yarn build --analyze
      - name: デプロイ
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
      - name: ビルドファイルの統計を保存
        uses: actions/upload-artifact@v1
        with:
          name: stats
          path: .nuxt/stats
