name: GitHub Pagesへのデプロイ
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ブランチをチェックアウト
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: パッケージインストール
        run: yarn install
      - name: 静的ビルド
        run: yarn generate
      - name: デプロイ
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
